# Generated by Django 5.0.3 on 2026-03-11 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0001_initial'),
        ('firms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='firms.lawfirm'),
        ),
    ]
